//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_OrderProducts
    {
        public int orderid { get; set; }
        public System.DateTime date { get; set; }
        public string comment { get; set; }
        public int clientid { get; set; }
        public int operatorid { get; set; }
        public int locationid { get; set; }
        public int orderitemid { get; set; }
        public int productid { get; set; }
        public string name { get; set; }
        public decimal price { get; set; }
    }
}
